### ISSUE TITLE
Add JOSS Badge to README

### ISSUE THREAD

**Issue by mpadge** [zabore/riskclustr#6]
Just noticed you don't have the JOSS badge on your README - it would be helpful if you could add the badge to link directly to the corresponding article:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01269/status.svg)](https://doi.org/10.21105/joss.01269)

**Comment by zabore** [comment]
Sorry for the delay, I was on maternity leave for the past few months and was not keeping up with things. I've added the badge to the README. Thanks!
